//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 103.160.204.11
        ///103.160.204.157
        ///103.160.204.191
        ///103.169.142.2
        ///103.169.142.33
        ///103.169.142.80
        ///103.169.142.110
        ///103.169.142.125
        ///103.169.142.128
        ///103.184.44.21
        ///103.184.45.43
        ///104.16.137.52
        ///104.16.139.41
        ///104.16.139.138
        ///104.16.141.36
        ///104.16.145.9
        ///104.16.148.55
        ///104.16.149.169
        ///104.16.230.42
        ///104.16.62.176
        ///104.18.0.1
        ///104.18.0.2
        ///104.18.0.3
        ///104.18.0.4
        ///104.18.0.5
        ///104.18.0.6
        ///104.18.0.7
        ///104.18.0.8
        ///104.18.0.9
        ///104.18.0.10
        ///104.18.0.11
        ///104.18.0.12
        ///104.18.0.13
        ///104.18.0.14
        ///104.18.0.15
        ///104.18.0.16        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cdn {
            get {
                return ResourceManager.GetString("cdn", resourceCulture);
            }
        }
    }
}
